### ISSUE TITLE
original repo 

### ISSUE THREAD

**Issue by dominion2** [MNeMoNiCuZ/joy-caption-batch#23]
The original app.py batch captioner worked so much better and faster than these newer version.  Could you please bring back that repo?

**Comment by MNeMoNiCuZ** [comment]
The original code is still there.
[batch-prealpha.py](https://github.com/MNeMoNiCuZ/joy-caption-batch/blob/main/batch-prealpha.py)

**Comment by dominion2** [comment]
> The original code is still there. [batch-prealpha.py](https://github.com/MNeMoNiCuZ/joy-caption-batch/blob/main/batch-prealpha.py)

The version before the current version ran so much faster. I was able to caption 30 photos in less than 5 minutes, now it takes 40 minutes using the batch-prealpha.py. I'm still using the same hardware.

**Comment by MNeMoNiCuZ** [comment]
## Changes
That script hasn't changed, and having the alpha 2 script available should not affect it.
I don't have any metrics for running the old version before.

> Running the pre-alpha now, on 20 images on a 3090 I get this: **[02:43<00:00,  8.16s/it]**

> Running the alpha2 now, on 20 images on a 3090 I get this: **[03:11<00:00,  9.59s/it]**

## Reverting
If you want to go back to before the alpha 2 submit, you can go back to this revision:
https://github.com/MNeMoNiCuZ/joy-caption-batch/commit/1c1d429b85d22bb592e9206892f6a206096abbc5

Following this guide:
https://stackoverflow.com/questions/7539130/go-to-a-particular-revision
`git checkout 1c1d429`

I got the old version and ran the same 20 images with the script in the old version.
> Running the pre-alpha in the reverted repo, on 20 images on a 3090 I get this: **[02:48<00:00,  8.44s/it]**

So the old version is actually slower for me.

But remember that the speed is dependent on the output of your captions. The more text the AI generates, the longer it takes. Shorter captions are output significantly faster. So there's always a bit of randomness to the captions due to this.

> Rerunning the pre-alpha in the reverted repo, on 20 images on a 3090 I get this: **[02:56<00:00,  8.80s/it]**


## Joy-Caption / Joy-Tagging?
You are certain you were running joy-caption, not joy-tagging? That one is much faster.

**Comment by dominion2** [comment]
My dumbass was using batch-alpha2.py on my 3070ti 12GB card.  It does work but extremely slow.  I tried out batch-prealpha.py with lowVRAM setting and worked perfectly.
